version: "3"
services:
  todo-it-postgres-test:
    image: postgres:13-alpine
    container_name: todo-it-postgres-test
    env_file:
      - .env.test

  todo-it-test:
    build: .
    container_name: todo-it-test
    env_file:
      - .env.test
    entrypoint: dockerize -wait tcp://todo-it-postgres-test:5432 -timeout 20s docker-entrypoint.sh
    command: bash -c "npm run test:migration:run && npm t"
    depends_on:
      - todo-it-postgres-test
