version: "3"
services:
  db_test:
    image: postgres
    container_name: db_test
    env_file:
      - .env.test

  node_app_test:
    build: .
    container_name: node_app_test
    env_file:
      - .env.test
    entrypoint: dockerize -wait tcp://db:5432 -timeout 20s docker-entrypoint.sh
    command: "npm run test"
    depends_on:
      - db_test
