version: "3"
services:
  todo-it-postgres:
    image: postgres:13-alpine
    container_name: todo-it-postgres
    ports:
      - 2345:5432
    env_file:
      - .env
    volumes:
      - todo-it-postgres:/var/lib/postgresql/data

  todo-it-production:
    container_name: todo-it-production
    build: .
    ports:
      - 5000:5000
    env_file:
      - .env
    volumes:
      - .:/usr/src
      - /usr/src/node_modules
    entrypoint: dockerize -wait tcp://db:5432 -timeout 20s docker-entrypoint.sh
    command: "npm run dev"
    depends_on:
      - todo-it-postgres

volumes:
  todo-it-postgres:
