version: "3"
services:
  db:
    image: postgres
    container_name: db
    ports:
      - 2345:5432
    env_file:
      - .env
    volumes:
      - db_volume:/var/lib/postgresql/data

  node_app:
    container_name: node_app
    build: .
    ports:
      - 5000:5000
    env_file:
      - .env.test
    volumes:
      - .:/usr/src
      - /usr/src/node_modules
    entrypoint: dockerize -wait tcp://db:5432 -timeout 20s docker-entrypoint.sh
    command: "npm run dev"
    depends_on:
      - db

volumes:
  db_volume:
